config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  authenticated :user do
    root to: 'store#index', as: :store_root
  end

  root to: 'visitors#index'

  resources :ovens do
    resource :cookies
    member do
      post :empty
    end
  end
end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
  belongs_to :storage, polymorphic: :true
  
  validates :storage, presence: true
end

app/models/oven.rb
class Oven < ActiveRecord::Base
  belongs_to :user
  has_one :cookie, as: :storage

  validates :user, presence: true

  def bake!
    cookie.update(ready: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ovens
  has_many :stored_cookies, class_name: 'Cookie', as: :storage

  before_create :setup_first_oven

  private

  def setup_first_oven
    ovens.new(name: 'My First Oven')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :basic_authenticate

  private

  def basic_authenticate
    return if Rails.env.test?

    authenticate_or_request_with_http_basic do |username, password|
      username == 'bake' && password == 'somecookies'
    end

  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    if @oven.cookie
      redirect_to @oven, alert: 'A cookie is already in the oven!'
    else
      @cookie = @oven.build_cookie
    end
  end

  def create
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    @cookie = @oven.create_cookie!(cookie_params)

    BakeJob.set(wait: BakeJob::TIME).perform_later(@oven)

    redirect_to oven_path(@oven)
  end

  private

  def cookie_params
    params.require(:cookie).permit(:fillings, :batch)
  end
end

app/controllers/ovens_controller.rb
class OvensController < ApplicationController
  before_action :authenticate_user!

  def index
    @ovens = current_user.ovens
  end

  def show
    @oven = current_user.ovens.find_by!(id: params[:id])
  end

  def empty
    @oven = current_user.ovens.find_by!(id: params[:id])
    if @oven.cookie
      @oven.cookie.update_attributes!(storage: current_user)
    end
    redirect_to @oven, alert: 'Oven emptied!'
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/ovens_helper.rb
module OvensHelper
end

app/views/cookies/new.html.haml
%h3 New Cookie for oven '#{@oven.name}'

= form_for [@oven, @cookie] do |f|
  .row
    .small-8.columns
      = f.label :fillings
  .row
    .small-8.columns
      = f.text_field :fillings
  .row
    .small-8.columns
      = f.label :batch, "Batch Size"
  .row
    .small-8.columns
      = f.text_field :batch
  .row
    .small-8.columns
      = f.submit 'Mix and bake', class: 'button'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
.contain-to-grid
  %nav.top-bar{"data-topbar" => true}
    %ul.title-area
      %li.name
        = link_to 'Home', root_path
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          Menu
    .top-bar-section
      %ul.right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to "Ovens", ovens_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Flowspace Bakery'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Flowspace Bakery'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .row
      %main{:role => "main"}
        = render 'layouts/messages'
        = yield

app/views/ovens/index.html.haml
%h3 My Ovens

%ul.ovens
  - @ovens.each do |oven|
    %li= link_to oven.name, oven

app/views/ovens/show.html.haml
.oven-channel{data: {oven: @oven.id}}
  - if browser.device.mobile?
    = link_to "Prepare Cookie", new_oven_cookies_path(@oven), class: 'button', style: 'margin-top: 1em;'

  %h3= @oven.name

  .cookie-info
    Cookie in oven:
    - if @oven.cookie
      #{pluralize(@oven.cookie.batch, "cookie")} with #{@oven.cookie.fillings.presence || "no fillings"}
      - if @oven.cookie.ready?
        (Your Cookie is Ready)
        = button_to "Retrieve Cookie", empty_oven_path(@oven), class: 'button tiny'
    - else
      None

  %br

  - unless browser.device.mobile?
    = link_to "Prepare Cookie", new_oven_cookies_path(@oven), class: 'button'

app/views/store/index.html.haml
%h3 Your Bakery

.bakery-nav
  = link_to "View your ovens", ovens_path

%br

.store-inventory
  Cookies for sale:
  %ul
    - current_user.stored_cookies.group_by(&:fillings).each_pair do |fillings, cookies|
      %li
        = pluralize(cookies.map(&:batch).sum, "Cookie")
        with
        = fillings.presence || "no filling"
    

app/views/visitors/index.html.haml
%h3 Welcome to the Flowspace Bakery